name: Build Xamarin.Forms.UWP app

on:
  pull_request:  
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

     # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies
      run: nuget restore Erni.Mobile.sln
      
    - name: Build
      run: msbuild src\CrossPlatform\Xamarin\Erni.Mobile.UWP\Erni.Mobile.UWP.csproj /p:Configuration=Debug /t:Rebuild     
